theme: jekyll-theme-minimal
title: Experimentel Fysik 2
description: >
  A portfolio of the projects made by, Jeppe Lykke Krogh and myself Frederik Rosendal Rytter, troughout the experimentel fysik 2 course. <br />
  In each project overview, a description of the project and the most important results are given. <br />
  The titles are links to the coresponding github repositories, where the code and more in depth explanations lie. <br />
